version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - emotions
    env_file: .env
    ports:
      - 5432:5432

  app:
    build: .
    env_file: .env
    networks:
      - backend
    ports:
      - 5001:5001

networks:
  emotions:
  backend:
